AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: deno_registry2

Resources:
  Deno:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno
        SemanticVersion: 1.2.0

  DenoHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"

  WebhookGithubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      MemorySize: 512
      Handler: bundle.handler
      Runtime: provided
      Layers:
        - !GetAtt Deno.Outputs.LayerArn
        - !Sub "arn:aws:lambda:${AWS::Region}:553035198032:layer:git-lambda2:6"
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StorageBucket
      Environment:
        Variables:
          DENO_UNSTABLE: 1
          HANDLER_EXT: js
          MONGO_URI: "{{resolve:secretsmanager:mongodb/atlas/deno_registry2:SecretString:MongoURI}}"
          STORAGE_BUCKET: !Ref StorageBucket
      Timeout: 60
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref DenoHttpApi
            Path: /webhook/gh/{name}
            Method: POST
    Metadata:
      BuildMethod: makefile

  ModulesListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      MemorySize: 128
      Handler: bundle.handler
      Runtime: provided
      Layers:
        - !GetAtt Deno.Outputs.LayerArn
      Environment:
        Variables:
          DENO_UNSTABLE: 1
          HANDLER_EXT: js
          MONGO_URI: "{{resolve:secretsmanager:mongodb/atlas/deno_registry2:SecretString:MongoURI}}"
      Timeout: 5
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref DenoHttpApi
            Path: /modules
            Method: GET
    Metadata:
      BuildMethod: makefile

  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET]
            AllowedOrigins: ["*"]

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${DenoHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  S3Bucket:
    Value: !Sub "${StorageBucket}.s3.${AWS::Region}.amazonaws.com"
