# This file was autogenerate by the BETA 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# All generated input variables will be of string type as this how Packer JSON
# views them; you can later on change their type. Read the variables type
# constraints documentation
# https://www.packer.io/docs/from-1.5/variables#type-constraints for more info.
variable "aws_access_key" {
  type    = string
}

variable "aws_secret_key" {
  type    = string
}

variable "region" {
  type    = string
}

# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors onto a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/from-1.5/blocks/source
source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.aws_access_key}"
  ami_name      = "meilisearch-custom-${local.timestamp}"
  instance_type = "t3a.small"
  region        = "${var.region}"
  secret_key    = "${var.aws_secret_key}"
  source_ami_filter {
    filters = {
      image-id = "ami-0edab43b6fa892279"
    }
    most_recent = true
    owners      = ["099720109477"]
  }
  ssh_username = "ubuntu"
}

# a build block invokes sources and runs provisionning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/from-1.5/blocks/build
build {
  sources = ["source.amazon-ebs.autogenerated_1"]
  provisioner "file" {
    destination = "meilisearch.service"
    source      = "./service"
  }
  provisioner "shell" {
    inline = [
      "whoami",
      "groups",
      "curl -L https://install.meilisearch.com | sh",
      "sudo mv ./meilisearch /usr/bin",
      "sudo mv ./meilisearch.service /etc/systemd/system/",
      "sudo mkdir -p /var/lib/meilisearch",
      "sudo systemctl enable meilisearch",
    ]
  }
}
