# Cloudflare Worker configuration
account_id = "93bfcf72dfea0e9f2bf5563bc71052cf"

# shared
type = "javascript"

# default dev environment
name = "cdn-dev"
workers_dev = true

# environment configuration
[env.production]
name = "cdn"
route = "cdn.deno.land/*"
workers_dev = false